### ISSUE TITLE
Issues with the "real world example"

### ISSUE THREAD

**Issue by benmoss** [metalbear-co/nodejs-example#3]
I'm trying to follow the [real world example](https://mirrord.dev/docs/overview/real-world-example/) tutorial to learn how to use mirrord.

First issue I ran into was running `yarn`:
```
$ yarn && yarn workspace auditor build

yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error openid-client@5.1.9: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "19
.5.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I found [this issue](https://github.com/nextauthjs/next-auth/discussions/4343) and ran `yarn add next-auth --ignore-engines` from the auditor directory, which seems to have fixed it and modified the auditor/package.json and yarn.lock files.

The next thing I'm stuck on now is running `mirrord exec` I get:

```
$ mirrord exec --target pod/example-auditor-7bd6d89444-ppzsk yarn -- workspace auditor start
⠴ mirrord cli starting
  ✓ ready to launch process
  ✓ layer extracted
  ✓ agent pod created
  ✓ pod is ready
/var/folders/k_/jld8nl213fxc5l3qs818z2z40000gn/T/mirrord-bin/bin/bash: /var/folders/k_/jld8nl213fxc5l3qs818z2z40000gn/T/mirrord-bin/opt/homebrew/bin/yarn: No such file or directory
```

Not sure what that's about, I wonder if it could be something about `yarn` being a symlink? I installed it with Homebrew.

**Comment by joelmgallant** [comment]
`Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "19.5.0"`

It looks like you're using an unsupported version of node (19.5) -- a release from the 16.x line should serve you better!

**Comment by benmoss** [comment]
I was just using what `brew install node` gave me. Not too familiar with the Node ecosystem.

For the second problem, I found someone else with a similar sounding issue in [the Discord](https://discord.com/channels/933706914808889356/1067847048403103884/1067847780334313583), and the suggested fix worked here too:
```
mirrord exec --fs-mode local --target pod/example-auditor-7bd6d89444-ppzsk yarn -- workspace auditor start
```

**Comment by joelmgallant** [comment]
It's relatively easy to install a specific version of node through brew as well:
https://formulae.brew.sh/formula/node@16
`brew install node@16`

**Comment by benmoss** [comment]
node@16 yields:

```
yarn && yarn workspace auditor build

yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 1.38s.
yarn workspace v1.22.19
yarn run v1.22.19
$ parcel build
Error: Unable to deserialize cloned data due to invalid or unsupported version.
    at deserialize (node:v8:380:7)
    at deserialize (/private/tmp/nodejs-example/node_modules/@parcel/core/lib/serializer.js:249:48)
    at loadRequestGraph (/private/tmp/nodejs-example/node_modules/@parcel/core/lib/RequestTracker.js:854:52)
    at async Function.init (/private/tmp/nodejs-example/node_modules/@parcel/core/lib/RequestTracker.js:821:17)
    at async Parcel._init (/private/tmp/nodejs-example/node_modules/@parcel/core/lib/Parcel.js:256:28)
    at async Parcel.run (/private/tmp/nodejs-example/node_modules/@parcel/core/lib/Parcel.js:273:7)
    at async run (/private/tmp/nodejs-example/node_modules/parcel/lib/cli.js:376:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /opt/homebrew/Cellar/node@16/16.19.0_1/bin/node
Arguments: /opt/homebrew/Cellar/yarn/1.22.19/libexec/lib/cli.js build
Directory: /private/tmp/nodejs-example/auditor
Output:
```

**Comment by benmoss** [comment]
More follow-up on Discord: https://discord.com/channels/933706914808889356/1067847048403103884

**Comment by t4lz** [comment]
https://github.com/metalbear-co/mirrord/issues/986 is for the `No such file or directory` part of this issue.

**Comment by aviramha** [comment]
Fixed with https://github.com/metalbear-co/mirrord/releases/tag/3.21.0 thanks for everyone involved :)

**Comment by t4lz** [comment]
> First issue I ran into was running `yarn`:

Should we maybe reopen this issue here, for either specifying compatible yarn versions in the example instructions, or adding to the instructions the step that solved that problem for OP? (`yarn add next-auth --ignore-engines`)

Or do we not expect those difficulties to arise for more users?

**Comment by aviramha** [comment]
> > First issue I ran into was running `yarn`:
> 
> Should we maybe reopen this issue here, for either specifying compatible yarn versions in the example instructions, or adding to the instructions the step that solved that problem for OP? (`yarn add next-auth --ignore-engines`)
> 
> Or do we not expect those difficulties to arise for more users?

Sorry didn't notice that. @DmitryDodzin Care to check this out ?
